services:
  backend-image:
    container_name: backend-container
    image: rbhagat32/echo-backend
    ports:
      - 4000:4000
    environment:
      - FRONTEND_URL_PROD=https://chat.void9.space
      - MONGODB_URI=mongodb+srv://rbhagat:rbhagat@first-backend-app.rd0h0uk.mongodb.net/chat-socket-io
      - JWT_SECRET=sdfarwegfaesdhfuaer
      - CLOUDINARY_CLOUD_NAME=dkyxlrmcg
      - CLOUDINARY_API_KEY=228997985731528
      - CLOUDINARY_API_SECRET=v7ICBGN1ULXJ59XNwCUYzg7X55E

  frontend-image:
    container_name: frontend-container
    image: rbhagat32/echo-frontend
    depends_on:
      - backend-image
    ports:
      - 4173:4173
