services:
  backend-image:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    env_file:
      - ./backend/.env
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore: "node_modules"
        - path: ./backend/package*.json
          action: rebuild

  frontend-image:
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend-image
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore: "node_modules/"
        - action: rebuild
          path: ./frontend/package*.json
