services:
  backend-image:
    container_name: backend-container
    image: rbhagat32/echo-backend
    ports:
      - 4000:4000
    env_file:
      - ./.env.backend

  frontend-image:
    container_name: frontend-container
    image: rbhagat32/echo-frontend
    depends_on:
      - backend-image
    ports:
      - 4173:4173
